### PR TITLE
Fix #271 Skip Non-NodeJS Functions

### LINKED ISSUE #271: ignore non nodejs functions
i saw that there was some effort with this issue, any chance we can verify the pr and merge it ?

https://github.com/serverless/serverless-plugin-typescript/pull/197

### PR DESCRIPTION
**Pull request by sazzy4o**
This plugin currently breaks your serverless stack if you have any non-nodejs functions (Python, Java, etc.) also in it. This skips them
This is based on this old PR: #197 (Merge conflicts and some unnecessary changes)
This closes #271

Change summary:
- Update to typescript 4.* (fixes tsc error I was getting before making any changes, I can revert if you don't want this update)
- Only grab functions of nodejs type (Fixes error this causes for non-nodejs functions)
- Add test (copied from #197)

### CODE REVIEW

**Comment by sazzy4o** [comment]
@medikoo Could you please review this PR?
(Sorry, if this is not the right way to request a review)

File: package.json [hunk 1]
```diff
@@ -53,13 +53,13 @@
     "@types/jest": "24.0.12",
     "@types/lodash": "4.14.123",
     "@types/node": "12.6.2",
-    "jest": "24.5.0",
```
Comment (medikoo) [inline package.json:56]: Is it required to upgrade `jest`?

I feel it's a breaking change for the suite, as in current  major support for Node.js v10 must be maintained and we should be able to run tests with that version

File: src/index.ts [hunk 2]
```diff
@@ -93,14 +93,25 @@ export class TypeScriptPlugin {
...
-    if (options.function) {
+    const nodeFunctions = Object.keys(functions)
+      .filter(functionKey => {
+        const runtime = functions[functionKey].runtime || service.provider.runtime
+        return runtime.includes('nodejs')
+      })
+      .reduce((obj, key) => {
+        obj[key] = functions[key]
+        return obj
+    }, {})
```
Comment (medikoo) [inline src/index.ts:106]: Let's not user reduce for that. It'll be clearer to setup loop as follows:

```javascript
const nodeFunctions = {};
for (const [name, functionObject] of Object.entries(functions)) {
  if (nodeRuntime) nodeFunctions[name] = functionObject;
}
```

**Review by medikoo — CHANGES_REQUESTED** [review]
Thank you @sazzy4o ! Please see my comments

File: package.json (hunk 1 above)
Comment (sazzy4o) [reply package.json]: Good catch, seems like the latest version of `jest` doesn't support Node.js v10. There is just a warning that typescript version is not officially supported:
```
ts-jest[versions] (WARN) Version 4.7.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
```

Comment (sazzy4o) [reply package.json]: Also, in case you were wondering why `typescript` was updated. It does not compile with `3.9.*`:
```
node_modules/@sinclair/typebox/typebox.d.ts:66:102 - error TS2574: A rest element type must be an array type.

66 export declare type StaticContructorParameters<T extends readonly TSchema[], P extends unknown[]> = [...{
                                                                                                        ~~~~
67     [K in keyof T]: T[K] extends TSchema ? Static<T[K], P> : never;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68 }];
   ~

node_modules/@sinclair/typebox/typebox.d.ts:87:100 - error TS2574: A rest element type must be an array type.

87 export declare type StaticFunctionParameters<T extends readonly TSchema[], P extends unknown[]> = [...{
                                                                                                      ~~~~
88     [K in keyof T]: T[K] extends TSchema ? Static<T[K], P> : never;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
89 }];
   ~

node_modules/@sinclair/typebox/typebox.d.ts:105:21 - error TS2456: Type alias 'IntersectReduce' circularly references itself.

105 export declare type IntersectReduce<I extends unknown, T extends readonly any[]> = T extends [infer A, ...infer B] ? IntersectReduce<I & A, B> : I extends object ? I : {};
                        ~~~~~~~~~~~~~~~

node_modules/@sinclair/typebox/typebox.d.ts:105:104 - error TS2574: A rest element type must be an array type.

105 export declare type IntersectReduce<I extends unknown, T extends readonly any[]> = T extends [infer A, ...infer B] ? IntersectReduce<I & A, B> : I extends object ? I : {};
                                                                                                           ~~~~~~~~~~

node_modules/@sinclair/typebox/typebox.d.ts:105:118 - error TS2315: Type 'IntersectReduce' is not generic.

105 export declare type IntersectReduce<I extends unknown, T extends readonly any[]> = T extends [infer A, ...infer B] ? IntersectReduce<I & A, B> : I extends object ? I : {};
...
```

File: src/index.ts (hunk 2 above)
Comment (sazzy4o) [reply src/index.ts]: Good idea, I refactored the logic

**Comment by sazzy4o** [comment]
@medikoo Thanks for the review. I have made some changes

**Review by medikoo — APPROVED** [review]
Thank you @sazzy4o 👍

**Comment by avivshafir** [comment]
I'm getting the following error
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

I think when specifying packaging individually option we reach this line
https://github.com/serverless/serverless-plugin-typescript/blob/master/src/index.ts#L281

and it doesn't seem to include the fix

**Comment by sazzy4o** [comment]
@avivshafir Could you please share your serverless.yml and your package-lock.json (so, I can check your commit hash)
Note: this change has not been released to npm(you need to install directly from GitHub if you want it)

**Comment by avivshafir** [comment]
@sazzy4o 

https://gist.github.com/avivshafir/b984c80879938c44a77dc907e72bc374

running version 2.1.4 of serverless-plugin-typescript
and serverless version 3.23.0

**Comment by avivshafir** [comment]
Seems like it's happening only when I'm setting the python lambda to use an image parameter

**Comment by sazzy4o** [comment]
I haven't had time to properly test yet, but you can try this fix:

https://github.com/sazzy4o/serverless-plugin-typescript/commit/b9d3ae40845d4e1a13e3de9fe289e0d2f14011d6

(I should have some time to test and create a PR over the next few days)
